# Generated by Django 4.2.1 on 2023-05-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpair', '0002_remove_projectpair_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpair',
            name='text',
            field=models.TextField(default='enter your occupation', max_length=255),
        ),
    ]
